### PR TITLE
convert to applet

### PR DESCRIPTION
**Pull request by aledj2**
This change is [Reviewable](https://reviewable.io/reviews/moka-guys/dnanexus_bcftools_stats/3)

### CODE REVIEW

**Review by RachelDuffin — CHANGES_REQUESTED** [review]
> Reviewed 2 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/moka-guys/dnanexus_bcftools_stats/3)* status: 2 of 5 files reviewed, 1 unresolved discussion (waiting on @aledj2)

*[a discussion](https://reviewable.io/reviews/moka-guys/dnanexus_bcftools_stats/3#-NR--wJY4qo7UqgcmN8Q:-NR--wJY4qo7UqgcmN8R:b1770v1) (no related file):*
Id suggest finding out whether the multiple VCFs are actually needed before releasing the app - if the filter_vcf_with_bedfile app isn't needed I don't think this app is actually needed

___

**Review by natashapinto — CHANGES_REQUESTED** [review]
> Reviewed 3 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/moka-guys/dnanexus_bcftools_stats/3)* status: all files reviewed, 3 unresolved discussions (waiting on @aledj2)

___
*[`dxapp.json` line 15 at r1](https://reviewable.io/reviews/moka-guys/dnanexus_bcftools_stats/3#-NR8PL30AdFiOZxSFnl0:-NR8PL30AdFiOZxSFnl1:b-2zzfhb) ([raw file](https://github.com/moka-guys/dnanexus_bcftools_stats/blob/d11ca6063f397c7cd00d18828aecd25e5f84bd0a/dxapp.json#L15)):*
> ```JSON
>       "help": "The BED filtered VCF file",
>       "class": "file",
>       "patterns": ["*.vcf*"],
> ```

should we make it accept gvcfs too, in case its needed for FH samples? I can't remember if both VCFs and GVCFs are produced for these samples
___
*[`dxapp.json` line 23 at r1](https://reviewable.io/reviews/moka-guys/dnanexus_bcftools_stats/3#-NR8Pk_i6NaXcO3uN2lj:-NR8Pk_i6NaXcO3uN2lk:bnj7hl0) ([raw file](https://github.com/moka-guys/dnanexus_bcftools_stats/blob/d11ca6063f397c7cd00d18828aecd25e5f84bd0a/dxapp.json#L23)):*
> ```JSON
>       "help": "The VCF file to calculate stats on if the \"preferred\" VCF is not provided",
>       "class": "file",
>       "patterns": ["*.vcf*"],
> ```

same as above

**Review by aledj2 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/moka-guys/dnanexus_bcftools_stats/3)* status: all files reviewed, 3 unresolved discussions (waiting on @natashapinto)

___
*[`dxapp.json` line 15 at r1](https://reviewable.io/reviews/moka-guys/dnanexus_bcftools_stats/3#-NR8PL30AdFiOZxSFnl0:-NR8STKHDq9GyRLBMGMF:b-6ud9m4) ([raw file](https://github.com/moka-guys/dnanexus_bcftools_stats/blob/d11ca6063f397c7cd00d18828aecd25e5f84bd0a/dxapp.json#L15)):*
<details><summary><i>Previously, natashapinto (Natasha Pinto) wrote…</i></summary><blockquote>

should we make it accept gvcfs too, in case its needed for FH samples? I can't remember if both VCFs and GVCFs are produced for these samples
</blockquote></details>

good point. but I think when a GVCF is created the VCF is always produced, and it's the VCF used to do bed filtering and any SNV analysis. GVCF only used for PRS. Assume this app wouldn't be useful in the snp pipeline
___
*[`dxapp.json` line 23 at r1](https://reviewable.io/reviews/moka-guys/dnanexus_bcftools_stats/3#-NR8Pk_i6NaXcO3uN2lj:-NR8SduY9fe-wnFFTPFs:b-9chp70) ([raw file](https://github.com/moka-guys/dnanexus_bcftools_stats/blob/d11ca6063f397c7cd00d18828aecd25e5f84bd0a/dxapp.json#L23)):*
<details><summary><i>Previously, natashapinto (Natasha Pinto) wrote…</i></summary><blockquote>

same as above
</blockquote></details>

as above

**Review by natashapinto — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/moka-guys/dnanexus_bcftools_stats/3)* status: all files reviewed, 1 unresolved discussion (waiting on @aledj2)

**Review by aledj2 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/moka-guys/dnanexus_bcftools_stats/3)* status: all files reviewed, 1 unresolved discussion (waiting on @RachelDuffin)

*[a discussion](https://reviewable.io/reviews/moka-guys/dnanexus_bcftools_stats/3#-NR--wJY4qo7UqgcmN8Q:-NR8YLQh8dIQb0ubeJig:b-896fix) (no related file):*
<details><summary><i>Previously, RachelDuffin wrote…</i></summary><blockquote>

Id suggest finding out whether the multiple VCFs are actually needed before releasing the app - if the filter_vcf_with_bedfile app isn't needed I don't think this app is actually needed
</blockquote></details>

Done.

___

**Review by natashapinto — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/moka-guys/dnanexus_bcftools_stats/3)* status: all files reviewed, 1 unresolved discussion (waiting on @RachelDuffin)

**Pull request merged**
